// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ljxrxxanhzptitkyaara.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqeHJ4eGFuaHpwdGl0a3lhYXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE4NDY5NjEsImV4cCI6MjA0NzQyMjk2MX0.uB46RdtcxRBW21SvWrxmw-m2ap78zW9zJeOFJ0n7oEE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);